CREATE TABLE user_sessions (
   id VARCHAR(255) PRIMARY KEY,
   user_id VARCHAR(255) REFERENCES users(id) ON DELETE CASCADE,
   refresh_token VARCHAR(255) UNIQUE NOT NULL,
   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   expires_at TIMESTAMP NOT NULL
);